### ISSUE TITLE
different PGxPOP outputs with same vcf input

### ISSUE THREAD

**Issue by jazberna1** [PharmGKB/PGxPOP#5] opened 2021-07-15 10:43 UTC
Hello PGxPOP team,

I have run PGxPOP v1.0 with the two vcf files attched wich in principle should be the same apart from some differences in the header related to the bcftools command used to generate them. However I found the PGxPOP output happens to be different. For instance:
The vcf file HG02236.a.vcf.gz gives me:
sample_id,gene,diplotype,
HG02236,CYP2C19,*1/*1

The vcf file HG02236.b.vcf.gz gives me:
HG02236,CYP2C19,*1/*2

This is how I run PGxPOP:
python bin/PGxPOP.py --vcf HG02236.a.vcf.gz -o HG02236.a.txt
python bin/PGxPOP.py --vcf HG02236.b.vcf.gz -o HG02236.b.txt

Is there something wrong I am doing you could think of? Any help will be much appreciated.

Many thanks
Jorge

[HG02236.a.vcf.gz](https://github.com/PharmGKB/PGxPOP/files/6822478/HG02236.a.vcf.gz)
[HG02236.b.vcf.gz](https://github.com/PharmGKB/PGxPOP/files/6822480/HG02236.b.vcf.gz)

[HG02236.b.txt](https://github.com/PharmGKB/PGxPOP/files/6822492/HG02236.b.txt)
[HG02236.a.txt](https://github.com/PharmGKB/PGxPOP/files/6822493/HG02236.a.txt)

**Comment by gregmcinnes** [comment] 2021-08-16 17:09
Hi there. I'm not able to reproduce this error on my machine. The results are identical for the two files you provided. Can you provide more information about how you encountered this error?

However, PGxPOP does produce much better results when the input data is phased. I would recommend computationally phasing the inputs using something like Eagle prior to running PGxPOP.

**Comment by alavertu** [comment] 2022-01-10 14:46
Closing until additional details are provided.

**Closed as completed by alavertu** 2022-01-10 14:46 UTC
